// UI strings for: checklists, notes, favorites, backup views + palette/search/card components.
// Filled by the i18n pass. Keys namespaced per area (e.g. "checklists.reset", "palette.placeholder").
const p: { ru: Record<string, string>; en: Record<string, string> } = {
  ru: {
    // ── scrolltop ──
    'scrolltop.title': 'Наверх',
    // ── searchfield ──
    'searchfield.clear': 'Очистить (Esc)',
    // ── card ──
    'card.favorite': 'В избранное',
    'card.saveFailed': 'Не сохранилось',
    'card.chipScheme': 'схема',
    'card.chipTable': 'таблица',
    'card.targetedHint': 'Примеры-хосты заменены на твою цель / LHOST',
    // ── palette ──
    'palette.placeholder': 'Поиск по всему, payloads, commands, GTFOBins, docs · ↵ открыть',
    'palette.clear': 'Очистить',
    'palette.navigate': 'навигация',
    'palette.open': 'открыть',
    'palette.copy': 'копировать',
    'palette.close': 'закрыть',
    'palette.hint': 'Поиск по всем пейлоадам, словарям и техникам…',
    'palette.noResults': 'Ничего не найдено',
    'palette.copyValue': 'Скопировать значение',
    'palette.copied': 'Скопировано · ',
    // ── backup ──
    'backup.exportFailed': 'Не удалось собрать бэкап: ',
    'backup.exportBtn': 'Скачать бэкап (JSON)',
    'backup.importBtn': 'Восстановить из файла…',
    'backup.readFailed': 'Не удалось прочитать файл — это не валидный JSON.',
    'backup.noEntries': 'В файле нет поля «entries» — похоже, это не бэкап ARS3NAL.',
    'backup.confirmHead': 'Восстановить из бэкапа?',
    'backup.confirmBody1': 'Это ЗАМЕНИТ все текущие данные содержимым файла',
    'backup.records': 'записей',
    'backup.confirmBody2': 'Текущее будет стёрто без возможности отмены.',
    'backup.restoring': 'Восстановление…',
    'backup.doneRestored': 'Готово: восстановлено',
    'backup.and': 'и',
    'backup.checklistMarks': 'отметок чек-листов',
    'backup.reloadHint': 'Обнови страницу (Ctrl+Shift+R).',
    'backup.restoreError': 'Ошибка восстановления: ',
    'backup.totalSuffix': 'всего',
    'backup.noServer': 'нет связи с сервером',
    'backup.title': 'Бэкап / восстановление',
    'backup.intro': 'Сохрани свой личный слой (заметки, готовые команды, избранное, прогресс и заметки чек-листов, цели и находки) в один JSON-файл. Справочный контент в бэкап не входит, он восстанавливается командой seed. Восстановление заменяет только твой личный слой, сид остаётся нетронутым.',
    'backup.nowInDb': 'Сейчас в базе',
    'backup.mergeBtn': 'Слить из файла…',
    'backup.confirmMergeHead': 'Слить бэкап с текущими данными?',
    'backup.confirmMergeBody': 'Твои записи и прогресс из файла добавятся к текущим. Ничего не удалится.',
    'backup.doneMerged': 'Готово: добавлено',
    'backup.mergedEntries': 'записей',
    'backup.mergedMarks': 'отметок',
    // ── favorites ──
    'favorites.typeNote': 'Заметка',
    'favorites.typeRecipe': 'Готовая команда',
    'favorites.searchPlaceholder': 'Поиск в избранном…',
    'favorites.title': 'Избранное',
    'favorites.untitled': '(без названия)',
    'favorites.remove': 'Убрать из избранного',
    'favorites.countSuffix': 'в избранном',
    'favorites.empty': 'В избранном пусто. Жми ★ на заметках, готовых командах, пейлоадах, GTFOBins и т.д. — всё собранное появится здесь.',
    // ── notes ──
    'notes.searchPlaceholder': 'Поиск заметок…',
    'notes.new': 'Новая',
    'notes.pluralOne': 'заметка',
    'notes.pluralFew': 'заметки',
    'notes.pluralMany': 'заметок',
    'notes.title': 'Notes',
    'notes.untitled': '(без названия)',
    'notes.untitledBare': 'без названия',
    'notes.confirmDelete1': 'Удалить заметку ',
    'notes.confirmDelete2': '?',
    'notes.emptyText': 'Заметок пока нет. Здесь — твои личные шпаргалки и заметки (markdown, таблицы, код).',
    'notes.createFirst': 'Создать первую заметку',
    'notes.toFav': 'В избранное',
    'notes.edit': 'Править',
    'notes.delete': 'Удалить',
    'notes.updated': 'обновлено',
    'notes.editTitle': 'Править заметку',
    'notes.newTitle': 'Новая заметка',
    'notes.phTitle': 'Заголовок',
    'notes.phCategory': 'категория (необязательно)',
    'notes.phTags': 'теги через запятую (необязательно)',
    'notes.phBody': 'Markdown… **жирный**, таблицы, ```bash\\n код \\n```',
    'notes.save': 'Сохранить',
    'notes.cancel': 'Отмена',
    'notes.preview': 'Предпросмотр',
    // ── checklists ──
    'checklists.filterPlaceholder': 'Фильтр чек-листов…',
    'checklists.noChecklist': 'Без чек-листа',
    'checklists.openPayloads': 'Открыть пейлоады',
    'checklists.pickLeft': 'Выбери чек-лист слева',
    'checklists.research': 'Ресёрч',
    'checklists.reset': 'Сбросить',
    'checklists.allPayloads': 'Все пейлоады',
    'checklists.notePlaceholder': 'Твои заметки, payload’ы, находки по этой цели…',
    'checklists.notesHeading': 'Заметки',
    'checklists.toastReset': 'Чек-лист сброшен',
    'checklists.toastResetFailed': 'Не удалось сбросить',
    'checklists.copy': 'Скопировать',
    'checklists.copied': 'Скопировано',
    'checklists.matchedPayloads': 'Подходящие пейлоады из базы',
    'checklists.showPayloads': 'Пейлоады',
    'checklists.hidePayloads': 'Скрыть',
    'checklists.openAllPayloads': 'Открыть все пейлоады:',
    'checklists.toastSaveFailed': 'Не сохранилось',
  },
  en: {
    // ── scrolltop ──
    'scrolltop.title': 'Scroll to top',
    // ── searchfield ──
    'searchfield.clear': 'Clear (Esc)',
    // ── card ──
    'card.favorite': 'Favorite',
    'card.saveFailed': 'Could not save',
    'card.chipScheme': 'diagram',
    'card.chipTable': 'table',
    'card.targetedHint': 'Example hosts replaced with your target / LHOST',
    // ── palette ──
    'palette.placeholder': 'Search everything, payloads, commands, GTFOBins, docs · ↵ open',
    'palette.clear': 'Clear',
    'palette.navigate': 'navigate',
    'palette.open': 'open',
    'palette.copy': 'copy',
    'palette.close': 'close',
    'palette.hint': 'Search across every payload, wordlist & technique…',
    'palette.noResults': 'No results',
    'palette.copyValue': 'Copy value',
    'palette.copied': 'Copied · ',
    // ── backup ──
    'backup.exportFailed': 'Could not build backup: ',
    'backup.exportBtn': 'Download backup (JSON)',
    'backup.importBtn': 'Restore from file…',
    'backup.readFailed': 'Could not read the file, it is not valid JSON.',
    'backup.noEntries': 'The file has no "entries" field, this does not look like an ARS3NAL backup.',
    'backup.confirmHead': 'Restore from backup?',
    'backup.confirmBody1': 'This will REPLACE all current data with the file contents',
    'backup.records': 'entries',
    'backup.confirmBody2': 'The current data will be wiped with no way to undo.',
    'backup.restoring': 'Restoring…',
    'backup.doneRestored': 'Done: restored',
    'backup.and': 'and',
    'backup.checklistMarks': 'checklist marks',
    'backup.reloadHint': 'Reload the page (Ctrl+Shift+R).',
    'backup.restoreError': 'Restore error: ',
    'backup.totalSuffix': 'total',
    'backup.noServer': 'no connection to server',
    'backup.title': 'Backup / restore',
    'backup.intro': 'Save your personal layer (notes, command recipes, favorites, checklist progress and notes, targets and findings) into a single JSON file. The reference content is not included; it is reproduced by seed. Restoring replaces only your personal layer; the seeded content stays intact.',
    'backup.nowInDb': 'Currently in the database',
    'backup.mergeBtn': 'Merge from file…',
    'backup.confirmMergeHead': 'Merge backup into the current data?',
    'backup.confirmMergeBody': 'Your entries and progress from the file are added to the current ones. Nothing is deleted.',
    'backup.doneMerged': 'Done: added',
    'backup.mergedEntries': 'entries',
    'backup.mergedMarks': 'marks',
    // ── favorites ──
    'favorites.typeNote': 'Note',
    'favorites.typeRecipe': 'Command recipe',
    'favorites.searchPlaceholder': 'Search favorites…',
    'favorites.title': 'Favorites',
    'favorites.untitled': '(untitled)',
    'favorites.remove': 'Remove from favorites',
    'favorites.countSuffix': 'in favorites',
    'favorites.empty': 'Favorites are empty. Hit ★ on notes, command recipes, payloads, GTFOBins, etc. and everything you collect shows up here.',
    // ── notes ──
    'notes.searchPlaceholder': 'Search notes…',
    'notes.new': 'New',
    'notes.pluralOne': 'note',
    'notes.pluralFew': 'notes',
    'notes.pluralMany': 'notes',
    'notes.title': 'Notes',
    'notes.untitled': '(untitled)',
    'notes.untitledBare': 'untitled',
    'notes.confirmDelete1': 'Delete note ',
    'notes.confirmDelete2': '?',
    'notes.emptyText': 'No notes yet. This is for your personal cheat sheets and notes (markdown, tables, code).',
    'notes.createFirst': 'Create the first note',
    'notes.toFav': 'Add to favorites',
    'notes.edit': 'Edit',
    'notes.delete': 'Delete',
    'notes.updated': 'updated',
    'notes.editTitle': 'Edit note',
    'notes.newTitle': 'New note',
    'notes.phTitle': 'Title',
    'notes.phCategory': 'category (optional)',
    'notes.phTags': 'tags, comma-separated (optional)',
    'notes.phBody': 'Markdown… **bold**, tables, ```bash\\n code \\n```',
    'notes.save': 'Save',
    'notes.cancel': 'Cancel',
    'notes.preview': 'Preview',
    // ── checklists ──
    'checklists.filterPlaceholder': 'Filter checklists…',
    'checklists.noChecklist': 'No checklist',
    'checklists.openPayloads': 'Open payloads',
    'checklists.pickLeft': 'Pick a checklist on the left',
    'checklists.research': 'Research',
    'checklists.reset': 'Reset',
    'checklists.allPayloads': 'All payloads',
    'checklists.notePlaceholder': 'Your notes, payloads, findings on this target…',
    'checklists.notesHeading': 'Notes',
    'checklists.toastReset': 'Checklist reset',
    'checklists.toastResetFailed': 'Could not reset',
    'checklists.copy': 'Copy',
    'checklists.copied': 'Copied',
    'checklists.matchedPayloads': 'Matching payloads from the database',
    'checklists.showPayloads': 'Payloads',
    'checklists.hidePayloads': 'Hide',
    'checklists.openAllPayloads': 'Open all payloads:',
    'checklists.toastSaveFailed': 'Could not save',
  },
};
export default p;
