// UI strings for reference views: payloads, gtfobins, wordlists, burp.
// Filled by the i18n pass. Keys namespaced per view (e.g. "payloads.filter").
const p: { ru: Record<string, string>; en: Record<string, string> } = {
  ru: {
    // payloads.ts (source placeholders were English UI chrome; ru is the translation)
    'payloads.filterCats': 'Фильтр категорий…',
    'payloads.filterInCat': 'Фильтр в этой категории…',
    'payloads.empty': 'Здесь пусто',
    'payloads.countPayloads': 'payload’ов',
    'payloads.targetPh': 'Цель: host или URL',
    'payloads.lhostPh': 'LHOST / коллектор',
    'payloads.targetBarHint': 'Задай цель: примеры-хосты в пейлоадах заменятся на неё',
    'payloads.new': 'Новый',
    'payloads.edit': 'Править',
    'payloads.delete': 'Удалить',
    'payloads.onlyMine': 'Только мои',
    'payloads.mineTag': 'моё',
    'payloads.confirmDelete': 'Удалить эту запись?',
    'payloads.formNew': 'Новый payload',
    'payloads.formEdit': 'Править payload',
    'payloads.phTitle': 'Заголовок',
    'payloads.phCategory': 'Категория',
    'payloads.phSubcategory': 'Подкатегория (необязательно)',
    'payloads.phLang': 'Язык: bash, http, js…',
    'payloads.phTags': 'теги через запятую',
    'payloads.phBody': 'Payload / код / текст',
    'payloads.save': 'Сохранить',
    'payloads.cancel': 'Отмена',
    'payloads.titleRequired': 'Нужен заголовок',

    // gtfobins.ts
    'gtfobins.searchPlaceholder': 'Поиск бинаря…',
    'gtfobins.creditPrefix': 'Данные — ',
    'gtfobins.funcLabel': 'Функции',
    'gtfobins.ctxLabel': 'Контексты',
    'gtfobins.pluralOne': 'бинарь',
    'gtfobins.pluralFew': 'бинаря',
    'gtfobins.pluralMany': 'бинарей',
    'gtfobins.copy': 'Copy',
    'gtfobins.notLoaded': '<p>GTFOBins ещё не загружены — выполни <code>npm run seed</code>.</p>',

    // wordlists.ts
    'wordlists.searchPlaceholder': 'Поиск словаря…',
    'wordlists.intro': 'Топовые словари: путь на Kali, ссылка на GitHub и для чего каждый нужен. Пути сверены на боевой системе (SecLists 2025.3).',
    'wordlists.whenLabel': 'Когда: ',
    'wordlists.copy': 'Copy',
    'wordlists.rawLink': 'Прямая ссылка ↗',
    'wordlists.searchTitle': 'Поиск',
    'wordlists.notFound': 'Ничего не найдено.',
    'wordlists.pluralOne': 'словарь',
    'wordlists.pluralFew': 'словаря',
    'wordlists.pluralMany': 'словарей',
    'wordlists.notLoaded': 'Справочник ещё не загружен — выполни npm run seed.',

    // burp.ts
    'burp.searchPlaceholder': 'Поиск по докам…',
    'burp.creditPrefix': 'На основе документации ',
    'burp.pluralOne': 'результат',
    'burp.pluralFew': 'результата',
    'burp.pluralMany': 'результатов',
    'burp.notFound': 'Ничего не найдено',
    'burp.copy': 'Copy',
    'burp.notLoaded': '<p>Документация ещё не загружена.</p>',
    'burp.notLoadedTitle': 'Burp Suite — документация',

    // scripts.ts
    'scripts.searchPlaceholder': 'Поиск скрипта…',
    'scripts.groupLabel': 'Раздел',
    'scripts.langLabel': 'Язык',
    'scripts.deps': 'Зависимости:',
    'scripts.params': 'Параметры:',
    'scripts.source': 'Источник ↗',
    'scripts.mustHave': 'must-have',
    'scripts.copy': 'Copy',
    'scripts.howto': 'Как пользоваться: скопируй код, поставь зависимости, подставь параметры и запусти командой из блока «Запуск».',
    'scripts.credit': 'Скрипты ARS3NAL · только для авторизованного тестирования · источники в карточках',
    'scripts.noneInFilter': 'Ничего не найдено',
    'scripts.resetFilters': 'Сбросить фильтры',
    'scripts.nothingFound': 'Ничего не найдено по текущим фильтрам.',
    'scripts.tip.must': 'Базовый, самый востребованный скрипт раздела',
    'scripts.tip.lang': 'Язык скрипта',
    'scripts.tip.destructive': 'Необратимые действия (запись / DoS / блокировки аккаунтов), только с явного разрешения',
    'scripts.tip.paid': 'Нужен платный ключ или подписка к внешнему сервису',
    'scripts.tip.http2': 'Требует поддержки HTTP/2 на цели',
    'scripts.tip.root': 'Требует root / повышенных прав на твоей машине',
    'scripts.tip.legacy': 'Старая или нишевая техника, работает не везде',
    'scripts.tip.oob': 'Нужен внешний OOB-сервер (Collaborator / interactsh)',
    'scripts.pluralOne': 'скрипт',
    'scripts.pluralFew': 'скрипта',
    'scripts.pluralMany': 'скриптов',
    'scripts.notLoaded': '<p>Скрипты ещё не загружены — выполни <code>npm run seed</code>.</p>',
  },
  en: {
    // payloads.ts
    'payloads.filterCats': 'Filter categories…',
    'payloads.filterInCat': 'Filter in this category…',
    'payloads.empty': 'Nothing here',
    'payloads.countPayloads': 'payloads',
    'payloads.targetPh': 'Target: host or URL',
    'payloads.lhostPh': 'LHOST / collector',
    'payloads.targetBarHint': 'Set a target and example hosts in payloads get replaced with it',
    'payloads.new': 'New',
    'payloads.edit': 'Edit',
    'payloads.delete': 'Delete',
    'payloads.onlyMine': 'Only mine',
    'payloads.mineTag': 'mine',
    'payloads.confirmDelete': 'Delete this entry?',
    'payloads.formNew': 'New payload',
    'payloads.formEdit': 'Edit payload',
    'payloads.phTitle': 'Title',
    'payloads.phCategory': 'Category',
    'payloads.phSubcategory': 'Subcategory (optional)',
    'payloads.phLang': 'Language: bash, http, js…',
    'payloads.phTags': 'tags, comma-separated',
    'payloads.phBody': 'Payload / code / text',
    'payloads.save': 'Save',
    'payloads.cancel': 'Cancel',
    'payloads.titleRequired': 'Title is required',

    // gtfobins.ts
    'gtfobins.searchPlaceholder': 'Search a binary…',
    'gtfobins.creditPrefix': 'Data from ',
    'gtfobins.funcLabel': 'Functions',
    'gtfobins.ctxLabel': 'Contexts',
    'gtfobins.pluralOne': 'binary',
    'gtfobins.pluralFew': 'binaries',
    'gtfobins.pluralMany': 'binaries',
    'gtfobins.copy': 'Copy',
    'gtfobins.notLoaded': '<p>GTFOBins are not loaded yet. Run <code>npm run seed</code>.</p>',

    // wordlists.ts
    'wordlists.searchPlaceholder': 'Search a wordlist…',
    'wordlists.intro': 'Top wordlists: Kali path, GitHub link and what each one is for. Paths verified on a live system (SecLists 2025.3).',
    'wordlists.whenLabel': 'When: ',
    'wordlists.copy': 'Copy',
    'wordlists.rawLink': 'Direct link ↗',
    'wordlists.searchTitle': 'Search',
    'wordlists.notFound': 'Nothing found.',
    'wordlists.pluralOne': 'wordlist',
    'wordlists.pluralFew': 'wordlists',
    'wordlists.pluralMany': 'wordlists',
    'wordlists.notLoaded': 'The reference is not loaded yet. Run npm run seed.',

    // burp.ts
    'burp.searchPlaceholder': 'Search the docs…',
    'burp.creditPrefix': 'Based on documentation from ',
    'burp.pluralOne': 'result',
    'burp.pluralFew': 'results',
    'burp.pluralMany': 'results',
    'burp.notFound': 'Nothing found',
    'burp.copy': 'Copy',
    'burp.notLoaded': '<p>Documentation is not loaded yet.</p>',
    'burp.notLoadedTitle': 'Burp Suite documentation',

    // scripts.ts
    'scripts.searchPlaceholder': 'Search a script…',
    'scripts.groupLabel': 'Group',
    'scripts.langLabel': 'Language',
    'scripts.deps': 'Dependencies:',
    'scripts.params': 'Parameters:',
    'scripts.source': 'Source ↗',
    'scripts.mustHave': 'must-have',
    'scripts.copy': 'Copy',
    'scripts.howto': 'How to use: copy the code, install the dependencies, fill in the parameters and run the command from the “Run” block.',
    'scripts.credit': 'ARS3NAL scripts · authorized testing only · sources in each card',
    'scripts.noneInFilter': 'Nothing found',
    'scripts.resetFilters': 'Reset filters',
    'scripts.nothingFound': 'Nothing matches the current filters.',
    'scripts.tip.must': 'Core, most-used script in this section',
    'scripts.tip.lang': 'Script language',
    'scripts.tip.destructive': 'Irreversible actions (writes / DoS / account lockout), only with explicit permission',
    'scripts.tip.paid': 'Needs a paid key or subscription to an external service',
    'scripts.tip.http2': 'Requires HTTP/2 support on the target',
    'scripts.tip.root': 'Needs root / elevated privileges on your machine',
    'scripts.tip.legacy': 'Old or niche technique, does not work everywhere',
    'scripts.tip.oob': 'Needs an external OOB server (Collaborator / interactsh)',
    'scripts.pluralOne': 'script',
    'scripts.pluralFew': 'scripts',
    'scripts.pluralMany': 'scripts',
    'scripts.notLoaded': '<p>Scripts are not loaded yet. Run <code>npm run seed</code>.</p>',
  },
};
export default p;
