// UI strings for reference views: payloads, gtfobins, wordlists, burp.
// Filled by the i18n pass. Keys namespaced per view (e.g. "payloads.filter").
const p: { ru: Record<string, string>; en: Record<string, string> } = {
  ru: {
    // payloads.ts (source placeholders were English UI chrome; ru is the translation)
    'payloads.filterCats': 'Фильтр категорий…',
    'payloads.filterInCat': 'Фильтр в этой категории…',
    'payloads.empty': 'Здесь пусто',
    'payloads.countPayloads': 'payload’ов',
    'payloads.targetPh': 'Цель: host или URL',
    'payloads.lhostPh': 'LHOST / коллектор',
    'payloads.targetBarHint': 'Задай цель: примеры-хосты в пейлоадах заменятся на неё',
    'payloads.new': 'Новый',
    'payloads.edit': 'Править',
    'payloads.delete': 'Удалить',
    'payloads.onlyMine': 'Только мои',
    'payloads.mineTag': 'моё',
    'payloads.confirmDelete': 'Удалить эту запись?',
    'payloads.formNew': 'Новый payload',
    'payloads.formEdit': 'Править payload',
    'payloads.phTitle': 'Заголовок',
    'payloads.phCategory': 'Категория',
    'payloads.phSubcategory': 'Подкатегория (необязательно)',
    'payloads.phLang': 'Язык: bash, http, js…',
    'payloads.phTags': 'теги через запятую',
    'payloads.phBody': 'Payload / код / текст',
    'payloads.save': 'Сохранить',
    'payloads.cancel': 'Отмена',
    'payloads.titleRequired': 'Нужен заголовок',

    // gtfobins.ts
    'gtfobins.searchPlaceholder': 'Поиск бинаря…',
    'gtfobins.creditPrefix': 'Данные — ',
    'gtfobins.funcLabel': 'Функции',
    'gtfobins.ctxLabel': 'Контексты',
    'gtfobins.pluralOne': 'бинарь',
    'gtfobins.pluralFew': 'бинаря',
    'gtfobins.pluralMany': 'бинарей',
    'gtfobins.copy': 'Copy',
    'gtfobins.notLoaded': '<p>GTFOBins ещё не загружены — выполни <code>npm run seed</code>.</p>',

    // wordlists.ts
    'wordlists.searchPlaceholder': 'Поиск словаря…',
    'wordlists.intro': 'Топовые словари: путь на Kali, ссылка на GitHub и для чего каждый нужен. Пути сверены на боевой системе (SecLists 2025.3).',
    'wordlists.whenLabel': 'Когда: ',
    'wordlists.copy': 'Copy',
    'wordlists.rawLink': 'Прямая ссылка ↗',
    'wordlists.searchTitle': 'Поиск',
    'wordlists.notFound': 'Ничего не найдено.',
    'wordlists.pluralOne': 'словарь',
    'wordlists.pluralFew': 'словаря',
    'wordlists.pluralMany': 'словарей',
    'wordlists.notLoaded': 'Справочник ещё не загружен — выполни npm run seed.',

    // burp.ts
    'burp.searchPlaceholder': 'Поиск по докам…',
    'burp.creditPrefix': 'На основе документации ',
    'burp.pluralOne': 'результат',
    'burp.pluralFew': 'результата',
    'burp.pluralMany': 'результатов',
    'burp.notFound': 'Ничего не найдено',
    'burp.copy': 'Copy',
    'burp.notLoaded': '<p>Документация ещё не загружена.</p>',
    'burp.notLoadedTitle': 'Burp Suite — документация',

    // scripts.ts
    'scripts.searchPlaceholder': 'Поиск скрипта…',
    'scripts.groupLabel': 'Раздел',
    'scripts.langLabel': 'Язык',
    'scripts.deps': 'Зависимости:',
    'scripts.params': 'Параметры:',
    'scripts.source': 'Источник ↗',
    'scripts.mustHave': 'must-have',
    'scripts.copy': 'Copy',
    'scripts.howto': 'Как пользоваться: скопируй код, поставь зависимости, подставь параметры и запусти командой из блока «Запуск».',
    'scripts.credit': 'Скрипты ARS3NAL · только для авторизованного тестирования · источники в карточках',
    'scripts.noneInFilter': 'Ничего не найдено',
    'scripts.resetFilters': 'Сбросить фильтры',
    'scripts.nothingFound': 'Ничего не найдено по текущим фильтрам.',
    'scripts.tip.must': 'Базовый, самый востребованный скрипт раздела',
    'scripts.tip.lang': 'Язык скрипта',
    'scripts.tip.destructive': 'Необратимые действия (запись / DoS / блокировки аккаунтов), только с явного разрешения',
    'scripts.tip.paid': 'Нужен платный ключ или подписка к внешнему сервису',
    'scripts.tip.http2': 'Требует поддержки HTTP/2 на цели',
    'scripts.tip.root': 'Требует root / повышенных прав на твоей машине',
    'scripts.tip.legacy': 'Старая или нишевая техника, работает не везде',
    'scripts.tip.oob': 'Нужен внешний OOB-сервер (Collaborator / interactsh)',
    'scripts.pluralOne': 'скрипт',
    'scripts.pluralFew': 'скрипта',
    'scripts.pluralMany': 'скриптов',
    'scripts.notLoaded': '<p>Скрипты ещё не загружены — выполни <code>npm run seed</code>.</p>',

    // chains.ts — Attack Chains
    'chains.searchPlaceholder': 'Поиск цепочки…',
    'chains.levelLabel': 'Уровень',
    'chains.level.newbie': 'Новичок',
    'chains.level.intermediate': 'Средний',
    'chains.level.advanced': 'Продвинутый',
    'chains.howto': 'Цепочки атак: путь от находки до импакта по шагам. Каждый шаг: цель, конкретный пейлоад или команда, и переход в нужный модуль одной кнопкой. Новичку: включи фильтр «Новичок» и иди снизу вверх.',
    'chains.noneInFilter': 'Ничего не найдено',
    'chains.resetFilters': 'Сбросить фильтры',
    'chains.nothingFound': 'Ничего не найдено по текущим фильтрам.',
    'chains.notLoaded': 'Цепочки ещё не загружены. Выполни npm run seed.',
    'chains.pluralOne': 'цепочка',
    'chains.pluralFew': 'цепочки',
    'chains.pluralMany': 'цепочек',
    'chains.copy': 'Copy',
    'chains.openIn': 'Открыть в',
    'chains.tokensTitle': 'Контекст цели',
    'chains.tokensHint': 'подставится в шаги: {USER_A}, {USER_B}, {CLIENT_ID}, {REDIRECT_URI}, {COLLAB}',
    'chains.copyPlaybook': 'Копировать playbook',
    'chains.collapseAll': 'Свернуть всё',
    'chains.expandAll': 'Развернуть всё',
    'chains.whyToggle': 'Почему это важно',
    'chains.showPayloads': 'Пейлоады',
    'chains.showScript': 'Скрипт',
    'chains.showCommand': 'Команда',
    'chains.showChecklist': 'Чеклист',
    'chains.noMatch': 'Совпадений не найдено',
    'chains.openAll': 'Открыть все',
    'chains.precondition': 'Когда применимо:',
    'chains.steps': 'Шаги',
    'chains.realWorld': 'Из реальных кейсов:',
    'chains.defense': 'Защита:',
    'chains.dismiss': 'Скрыть',
    'chains.altStep': 'альтернатива',
    // oauthlab.ts
    'oauth.howto': 'OAuth/SSO Lab: офлайн-крафтер. Выбери флоу, задай параметры, собери authorize URL и скопируй в браузер или Burp. Ниже дерево векторов с готовым пейлоадом и признаком успеха. Сам инструмент ничего не отправляет.',
    'oauth.authz': 'authorize endpoint',
    'oauth.copy': 'Copy',
    'oauth.success': 'Признак успеха:',
    'oauth.urlHint': 'Вставь в адресную строку жертвы, залогиненной в IdP, или в Burp. {CLIENT_ID}, {REDIRECT_URI}, {COLLAB} подставляются из токенов контекста.',
    'oauth.apply': 'Применить к URL',
    'oauth.applied': 'Применено ✓',
    'oauth.resetUrl': 'Сбросить URL',
    'oauth.step1': '1. Флоу',
    'oauth.step2': '2. Параметры',
    'oauth.step3': '3. Authorize URL',
    'oauth.step4': '4. Векторы атак',
    // jwtlab.ts
    'jwt.howto': 'JWT Workshop: клиентский инструмент. Вставь токен, он декодируется (без проверки), правь header и payload, потом применяй атаки: alg:none, RS256 → HS256 confusion, kid-трюки, переподпись слабым секретом. Всё в браузере, готовый токен копируешь в Burp.',
    'jwt.pasteLabel': 'Вставь JWT (декодируется автоматически)',
    'jwt.attacksTitle': 'Атаки и переподпись',
    'jwt.outTitle': 'Готовый токен',
    'jwt.algNone': 'alg:none',
    'jwt.algNoneTip': 'Снять подпись: alg=none, пустая подпись',
    'jwt.kidTrav': 'kid: traversal',
    'jwt.kidTravTip': 'kid=../../../../dev/null → пустой HMAC-ключ',
    'jwt.kidSqli': 'kid: SQLi',
    'jwt.kidSqliTip': 'SQL-инъекция в kid для подмены ключа',
    'jwt.kidJku': 'jku spoof',
    'jwt.kidJkuTip': 'jku на твой JWKS (через {COLLAB})',
    'jwt.sign': 'Подписать',
    'jwt.signTip': 'HS256-подпись заданным секретом',
    'jwt.secretPh': 'секрет (напр. secret, password, ключ из брута)',
    'jwt.confusion': 'RS256 → HS256 confusion',
    'jwt.forge': 'Подписать публичным ключом',
    'jwt.confusionTip': 'HMAC-подпись публичным RSA-ключом (key confusion)',
    'jwt.copy': 'Copy',
    'jwt.useAsInput': 'В поле ввода',
    'jwt.useAsInputTip': 'Загрузить готовый токен обратно для следующей итерации',
    'jwt.loaded': 'Загружено',
    'jwt.decoded': 'Декодировано',
    'jwt.badToken': 'Не похоже на JWT (нужны части через точку)',
    'jwt.badJson': 'Невалидный JSON в header или payload',
    'jwt.kidSet': 'Применено к header',
    'jwt.kidRemoved': 'Убрано из header',
    'jwt.copied': 'Скопировано',
    'jwt.attacksHint': 'Кнопки атак это переключатели: нажал = применил (подсветится), нажал ещё раз = убрал.',
    'jwt.claimsTitle': 'Быстрые claims:',
    'jwt.claimSet': 'Claim применён',
    'jwt.claimRemoved': 'Claim убран',
    'jwt.claimTip': 'Поставить клейм в payload',
    'jwt.claimExpTip': 'exp на час вперёд',
    'jwt.forgedNone': 'Готово: alg:none, подпись убрана',
    'jwt.signedSecret': 'Подписано HS256 секретом',
    'jwt.forgedConfusion': 'Готово: HS256 публичным ключом (confusion)',
    'jwt.needResign': 'Токен устарел: переподпиши',
    // reports.ts
    'reports.searchPlaceholder': 'Поиск шаблона…',
    'reports.howto': 'Шаблоны отчётов: каркас под каждый класс бага (описание, шаги, PoC, влияние, CVSS, CWE, рекомендации). Активная цель из Engagements и токены ({TARGET}, {USER_A}, {USER_B}) подставляются в текст. Копируй или экспортируй в .md и дописывай.',
    'reports.copyAll': 'Копировать отчёт',
    'reports.export': 'Экспорт .md',
    'reports.exportTip': 'Скачать шаблон как markdown-файл',
    'reports.copy': 'Copy',
    'reports.ctxHint': 'Цель и токены подставляются автоматически из активного Engagement или панели контекста.',
    'reports.sevLabel': 'Severity',
    'reports.unfilled': 'незаполненных токенов (заполни перед отправкой)',
    'reports.none': 'Ничего не найдено',
    'reports.pluralOne': 'шаблон',
    'reports.pluralFew': 'шаблона',
    'reports.pluralMany': 'шаблонов',
    'reports.notLoaded': '<p>Шаблоны ещё не загружены, выполни <code>npm run seed</code>.</p>',
  },
  en: {
    // payloads.ts
    'payloads.filterCats': 'Filter categories…',
    'payloads.filterInCat': 'Filter in this category…',
    'payloads.empty': 'Nothing here',
    'payloads.countPayloads': 'payloads',
    'payloads.targetPh': 'Target: host or URL',
    'payloads.lhostPh': 'LHOST / collector',
    'payloads.targetBarHint': 'Set a target and example hosts in payloads get replaced with it',
    'payloads.new': 'New',
    'payloads.edit': 'Edit',
    'payloads.delete': 'Delete',
    'payloads.onlyMine': 'Only mine',
    'payloads.mineTag': 'mine',
    'payloads.confirmDelete': 'Delete this entry?',
    'payloads.formNew': 'New payload',
    'payloads.formEdit': 'Edit payload',
    'payloads.phTitle': 'Title',
    'payloads.phCategory': 'Category',
    'payloads.phSubcategory': 'Subcategory (optional)',
    'payloads.phLang': 'Language: bash, http, js…',
    'payloads.phTags': 'tags, comma-separated',
    'payloads.phBody': 'Payload / code / text',
    'payloads.save': 'Save',
    'payloads.cancel': 'Cancel',
    'payloads.titleRequired': 'Title is required',

    // gtfobins.ts
    'gtfobins.searchPlaceholder': 'Search a binary…',
    'gtfobins.creditPrefix': 'Data from ',
    'gtfobins.funcLabel': 'Functions',
    'gtfobins.ctxLabel': 'Contexts',
    'gtfobins.pluralOne': 'binary',
    'gtfobins.pluralFew': 'binaries',
    'gtfobins.pluralMany': 'binaries',
    'gtfobins.copy': 'Copy',
    'gtfobins.notLoaded': '<p>GTFOBins are not loaded yet. Run <code>npm run seed</code>.</p>',

    // wordlists.ts
    'wordlists.searchPlaceholder': 'Search a wordlist…',
    'wordlists.intro': 'Top wordlists: Kali path, GitHub link and what each one is for. Paths verified on a live system (SecLists 2025.3).',
    'wordlists.whenLabel': 'When: ',
    'wordlists.copy': 'Copy',
    'wordlists.rawLink': 'Direct link ↗',
    'wordlists.searchTitle': 'Search',
    'wordlists.notFound': 'Nothing found.',
    'wordlists.pluralOne': 'wordlist',
    'wordlists.pluralFew': 'wordlists',
    'wordlists.pluralMany': 'wordlists',
    'wordlists.notLoaded': 'The reference is not loaded yet. Run npm run seed.',

    // burp.ts
    'burp.searchPlaceholder': 'Search the docs…',
    'burp.creditPrefix': 'Based on documentation from ',
    'burp.pluralOne': 'result',
    'burp.pluralFew': 'results',
    'burp.pluralMany': 'results',
    'burp.notFound': 'Nothing found',
    'burp.copy': 'Copy',
    'burp.notLoaded': '<p>Documentation is not loaded yet.</p>',
    'burp.notLoadedTitle': 'Burp Suite documentation',

    // scripts.ts
    'scripts.searchPlaceholder': 'Search a script…',
    'scripts.groupLabel': 'Group',
    'scripts.langLabel': 'Language',
    'scripts.deps': 'Dependencies:',
    'scripts.params': 'Parameters:',
    'scripts.source': 'Source ↗',
    'scripts.mustHave': 'must-have',
    'scripts.copy': 'Copy',
    'scripts.howto': 'How to use: copy the code, install the dependencies, fill in the parameters and run the command from the “Run” block.',
    'scripts.credit': 'ARS3NAL scripts · authorized testing only · sources in each card',
    'scripts.noneInFilter': 'Nothing found',
    'scripts.resetFilters': 'Reset filters',
    'scripts.nothingFound': 'Nothing matches the current filters.',
    'scripts.tip.must': 'Core, most-used script in this section',
    'scripts.tip.lang': 'Script language',
    'scripts.tip.destructive': 'Irreversible actions (writes / DoS / account lockout), only with explicit permission',
    'scripts.tip.paid': 'Needs a paid key or subscription to an external service',
    'scripts.tip.http2': 'Requires HTTP/2 support on the target',
    'scripts.tip.root': 'Needs root / elevated privileges on your machine',
    'scripts.tip.legacy': 'Old or niche technique, does not work everywhere',
    'scripts.tip.oob': 'Needs an external OOB server (Collaborator / interactsh)',
    'scripts.pluralOne': 'script',
    'scripts.pluralFew': 'scripts',
    'scripts.pluralMany': 'scripts',
    'scripts.notLoaded': '<p>Scripts are not loaded yet. Run <code>npm run seed</code>.</p>',

    // chains.ts — Attack Chains
    'chains.searchPlaceholder': 'Search a chain…',
    'chains.levelLabel': 'Level',
    'chains.level.newbie': 'Newbie',
    'chains.level.intermediate': 'Intermediate',
    'chains.level.advanced': 'Advanced',
    'chains.howto': 'Attack chains: from a finding to impact, step by step. Each step has a goal, a concrete payload or command, and a one-click jump into the right module. New here? Turn on the “Newbie” filter and climb from there.',
    'chains.noneInFilter': 'Nothing found',
    'chains.resetFilters': 'Reset filters',
    'chains.nothingFound': 'Nothing matches the current filters.',
    'chains.notLoaded': 'Chains are not loaded yet. Run npm run seed.',
    'chains.pluralOne': 'chain',
    'chains.pluralFew': 'chains',
    'chains.pluralMany': 'chains',
    'chains.copy': 'Copy',
    'chains.openIn': 'Open in',
    'chains.tokensTitle': 'Target context',
    'chains.tokensHint': 'fills chain steps: {USER_A}, {USER_B}, {CLIENT_ID}, {REDIRECT_URI}, {COLLAB}',
    'chains.copyPlaybook': 'Copy playbook',
    'chains.collapseAll': 'Collapse all',
    'chains.expandAll': 'Expand all',
    'chains.whyToggle': 'Why it matters',
    'chains.showPayloads': 'Payloads',
    'chains.showScript': 'Script',
    'chains.showCommand': 'Command',
    'chains.showChecklist': 'Checklist',
    'chains.noMatch': 'No matches found',
    'chains.openAll': 'Open all',
    'chains.precondition': 'When it applies:',
    'chains.steps': 'Steps',
    'chains.realWorld': 'Real-world cases:',
    'chains.defense': 'Defense:',
    'chains.dismiss': 'Dismiss',
    'chains.altStep': 'alternative',
    // oauthlab.ts
    'oauth.howto': 'OAuth/SSO Lab: an offline crafter. Pick a flow, set the params, assemble an authorize URL and copy it into a browser or Burp. Below is a tree of attack vectors with a ready payload and the success marker. The tool itself never sends anything.',
    'oauth.authz': 'authorize endpoint',
    'oauth.copy': 'Copy',
    'oauth.success': 'Success marker:',
    'oauth.urlHint': 'Paste it into the address bar of a victim logged into the IdP, or into Burp. {CLIENT_ID}, {REDIRECT_URI}, {COLLAB} fill in from the context tokens.',
    'oauth.apply': 'Apply to URL',
    'oauth.applied': 'Applied ✓',
    'oauth.resetUrl': 'Reset URL',
    'oauth.step1': '1. Flow',
    'oauth.step2': '2. Parameters',
    'oauth.step3': '3. Authorize URL',
    'oauth.step4': '4. Attack vectors',
    // jwtlab.ts
    'jwt.howto': 'JWT Workshop: a client-side crafter. Paste a token, decode (no verify), edit header/payload, then forge: alg:none, RS256→HS256 confusion, kid tricks, re-sign with a weak secret. All in the browser; copy the forged token into Burp.',
    'jwt.pasteLabel': 'Paste a JWT (decodes automatically)',
    'jwt.attacksTitle': 'Attacks and re-signing',
    'jwt.outTitle': 'Forged token',
    'jwt.algNone': 'alg:none',
    'jwt.algNoneTip': 'Strip the signature: alg=none, empty signature',
    'jwt.kidTrav': 'kid: traversal',
    'jwt.kidTravTip': 'kid=../../../../dev/null → empty HMAC key',
    'jwt.kidSqli': 'kid: SQLi',
    'jwt.kidSqliTip': 'SQL injection in kid to control the key',
    'jwt.kidJku': 'jku spoof',
    'jwt.kidJkuTip': 'point jku at your JWKS (via {COLLAB})',
    'jwt.sign': 'Sign',
    'jwt.signTip': 'HS256-sign with the given secret',
    'jwt.secretPh': 'secret (e.g. secret, password, a brute-forced key)',
    'jwt.confusion': 'RS256 → HS256 confusion',
    'jwt.forge': 'Forge',
    'jwt.confusionTip': 'HMAC-sign with the RSA public key (key confusion)',
    'jwt.copy': 'Copy',
    'jwt.useAsInput': 'To input',
    'jwt.useAsInputTip': 'Load the forged token back for the next iteration',
    'jwt.loaded': 'Loaded',
    'jwt.decoded': 'Decoded',
    'jwt.badToken': 'Does not look like a JWT (need dot-separated parts)',
    'jwt.badJson': 'Invalid JSON in header or payload',
    'jwt.kidSet': 'Applied to header',
    'jwt.kidRemoved': 'Removed from header',
    'jwt.copied': 'Copied',
    'jwt.attacksHint': 'The attack buttons are toggles: click to apply (it stays lit), click again to remove.',
    'jwt.claimsTitle': 'Quick claims:',
    'jwt.claimSet': 'Claim set',
    'jwt.claimRemoved': 'Claim removed',
    'jwt.claimTip': 'Set this claim in the payload',
    'jwt.claimExpTip': 'exp one hour ahead',
    'jwt.forgedNone': 'Done: alg:none, signature removed',
    'jwt.signedSecret': 'Signed with the HS256 secret',
    'jwt.forgedConfusion': 'Done: HS256 with the public key (confusion)',
    'jwt.needResign': 'Token is stale: re-sign it',
    // reports.ts
    'reports.searchPlaceholder': 'Search a template…',
    'reports.howto': 'Report templates: a skeleton per bug class (summary, steps, PoC, impact, CVSS, CWE, remediation). The active target from Engagements and the tokens ({TARGET}, {USER_A}, {USER_B}) substitute into the text. Copy or export to .md and fill in.',
    'reports.copyAll': 'Copy report',
    'reports.export': 'Export .md',
    'reports.exportTip': 'Download the template as a markdown file',
    'reports.copy': 'Copy',
    'reports.ctxHint': 'Target and tokens fill in automatically from the active Engagement or context panel.',
    'reports.sevLabel': 'Severity',
    'reports.unfilled': 'unfilled tokens (fill before you submit)',
    'reports.none': 'Nothing found',
    'reports.pluralOne': 'template',
    'reports.pluralFew': 'templates',
    'reports.pluralMany': 'templates',
    'reports.notLoaded': '<p>Templates are not loaded yet. Run <code>npm run seed</code>.</p>',
  },
};
export default p;
