// UI strings for tool/workspace views: commands, revshell, cyberchef, engage.
// Filled by the i18n pass. Keys namespaced per view (e.g. "commands.target").
const p: { ru: Record<string, string>; en: Record<string, string> } = {
  ru: {
    // ── commands ──
    'commands.targetPh': '10.10.11.50 · target.htb · http://…',
    'commands.lhostPh': 'ваш IP (LHOST)',
    'commands.target': 'Target',
    'commands.lhost': 'LHOST',
    'commands.barHint': 'подставляется в команды и сборщик',
    'commands.searchPh': 'Поиск по тулзам…',
    'commands.title': 'Commands',
    'commands.notFound': 'Ничего не найдено',
    'commands.result1': 'результат',
    'commands.result2': 'результата',
    'commands.result5': 'результатов',
    'commands.copy': 'Copy',
    'commands.install': 'Установка',
    'commands.resetTitle': 'Снять все флаги и вернуть значения к примерам',
    'commands.reset': '↺ Сброс',
    'commands.saveTitle': 'Сохранить собранную команду в рецепты (в базу)',
    'commands.save': '★ В рецепты',
    'commands.buildLabel': '⚙ Сборка команды',
    'commands.buildHint': 'тыкай флаги ниже — они попадают в команду',
    'commands.recipes': 'Готовые команды',
    'commands.collapse': 'свернуть',
    'commands.expand': 'развернуть',
    'commands.drag': 'Перетащить',
    'commands.delRecipe': 'Удалить рецепт',
    'commands.notSeeded': 'Справочник ещё не загружен — выполни <code>npm run seed</code>.',

    // ── revshell ──
    'revshell.tabReverse': 'Reverse',
    'revshell.tabBind': 'Bind',
    'revshell.tabAssembled': 'Assembled',
    'revshell.osAll': 'All',
    'revshell.portPlus1': 'port +1',
    'revshell.ipPort': 'IP & Port',
    'revshell.ipLhost': 'IP / LHOST',
    'revshell.port': 'Port',
    'revshell.listener': 'Listener',
    'revshell.type': 'Type',
    'revshell.searchPh': 'Поиск (bash, python, powershell…)',
    'revshell.os': 'ОС',
    'revshell.shell': 'Shell',
    'revshell.encoding': 'Encoding',
    'revshell.empty': 'Пусто',
    'revshell.pickLeft': 'Выбери тип слева',
    'revshell.raw': 'Raw',
    'revshell.copy': 'Copy',

    // ── engage ──
    'engage.newTarget': '＋ Цель',
    'engage.leftHead': 'Цели / engagements',
    'engage.title': 'Engagements',
    'engage.activeDot': 'активная цель',
    'engage.noTargets': 'целей пока нет',
    'engage.noName': '(без имени)',
    'engage.defaultTargetName': 'Новая цель',
    'engage.targetCreated': 'Цель создана',
    'engage.activePrefix': 'Активная цель: ',
    'engage.delTargetConfirm': 'Удалить цель «{name}» и все её находки ({count})?',
    'engage.notSaved': 'Не сохранилось',
    'engage.findingTitlePh': 'Заголовок находки',
    'engage.findingUrlPh': 'URL / эндпоинт',
    'engage.findingBodyPh': 'Repro / детали (markdown)',
    'engage.delFindingTitle': 'Удалить находку',
    'engage.delFindingConfirm': 'Удалить находку?',
    'engage.defaultFindingTitle': 'Новая находка',
    'engage.reportNotes': '## Заметки',
    'engage.reportFindings': '## Находки',
    'engage.reportStatus': '- **Статус:** ',
    'engage.reportDownloaded': 'Отчёт скачан',
    'engage.emptyDesc': 'Рабочее пространство по целям: хост/LHOST/scope, заметки и находки на каждую цель, экспорт отчёта в Markdown.',
    'engage.createFirst': '＋ Создать первую цель',
    'engage.activeBadge': '● активная',
    'engage.makeActive': '● Сделать активной',
    'engage.reportTitle': 'Экспорт отчёта (Markdown)',
    'engage.report': '⤓ Отчёт',
    'engage.delTargetTitle': 'Удалить цель',
    'engage.namePh': 'Имя цели / программы / бокса',
    'engage.notesPh': 'Заметки по цели (markdown): креды, порты, зацепки…',
    'engage.name': 'Имя',
    'engage.status': 'Статус',
    'engage.hostLabel': 'Host / IP  →  {TARGET}',
    'engage.lhostLabel': 'LHOST  →  {LHOST}',
    'engage.scope': 'Scope',
    'engage.scopePh': '*.target.com, in-scope hosts…',
    'engage.findingsHead': 'Находки',
    'engage.addFinding': '＋ Находка',
    'engage.notesHead': '🗒 Заметки',
    'engage.noFindings': 'находок пока нет — добавь первую',
  },
  en: {
    // ── commands ──
    'commands.targetPh': '10.10.11.50 · target.htb · http://…',
    'commands.lhostPh': 'your IP (LHOST)',
    'commands.target': 'Target',
    'commands.lhost': 'LHOST',
    'commands.barHint': 'substituted into commands and the builder',
    'commands.searchPh': 'Search tools…',
    'commands.title': 'Commands',
    'commands.notFound': 'Nothing found',
    'commands.result1': 'result',
    'commands.result2': 'results',
    'commands.result5': 'results',
    'commands.copy': 'Copy',
    'commands.install': 'Install',
    'commands.resetTitle': 'Clear all flags and reset values to examples',
    'commands.reset': '↺ Reset',
    'commands.saveTitle': 'Save the assembled command to recipes (to the database)',
    'commands.save': '★ To recipes',
    'commands.buildLabel': '⚙ Command builder',
    'commands.buildHint': 'click the flags below - they go into the command',
    'commands.recipes': 'Ready-made commands',
    'commands.collapse': 'collapse',
    'commands.expand': 'expand',
    'commands.drag': 'Drag',
    'commands.delRecipe': 'Delete recipe',
    'commands.notSeeded': 'Reference not loaded yet - run <code>npm run seed</code>.',

    // ── revshell ──
    'revshell.tabReverse': 'Reverse',
    'revshell.tabBind': 'Bind',
    'revshell.tabAssembled': 'Assembled',
    'revshell.osAll': 'All',
    'revshell.portPlus1': 'port +1',
    'revshell.ipPort': 'IP & Port',
    'revshell.ipLhost': 'IP / LHOST',
    'revshell.port': 'Port',
    'revshell.listener': 'Listener',
    'revshell.type': 'Type',
    'revshell.searchPh': 'Search (bash, python, powershell…)',
    'revshell.os': 'OS',
    'revshell.shell': 'Shell',
    'revshell.encoding': 'Encoding',
    'revshell.empty': 'Empty',
    'revshell.pickLeft': 'Pick a type on the left',
    'revshell.raw': 'Raw',
    'revshell.copy': 'Copy',

    // ── engage ──
    'engage.newTarget': '＋ Target',
    'engage.leftHead': 'Targets / engagements',
    'engage.title': 'Engagements',
    'engage.activeDot': 'active target',
    'engage.noTargets': 'no targets yet',
    'engage.noName': '(no name)',
    'engage.defaultTargetName': 'New target',
    'engage.targetCreated': 'Target created',
    'engage.activePrefix': 'Active target: ',
    'engage.delTargetConfirm': 'Delete target "{name}" and all its findings ({count})?',
    'engage.notSaved': 'Not saved',
    'engage.findingTitlePh': 'Finding title',
    'engage.findingUrlPh': 'URL / endpoint',
    'engage.findingBodyPh': 'Repro / details (markdown)',
    'engage.delFindingTitle': 'Delete finding',
    'engage.delFindingConfirm': 'Delete finding?',
    'engage.defaultFindingTitle': 'New finding',
    'engage.reportNotes': '## Notes',
    'engage.reportFindings': '## Findings',
    'engage.reportStatus': '- **Status:** ',
    'engage.reportDownloaded': 'Report downloaded',
    'engage.emptyDesc': 'Per-target workspace: host/LHOST/scope, notes and findings for each target, report export to Markdown.',
    'engage.createFirst': '＋ Create the first target',
    'engage.activeBadge': '● active',
    'engage.makeActive': '● Make active',
    'engage.reportTitle': 'Export report (Markdown)',
    'engage.report': '⤓ Report',
    'engage.delTargetTitle': 'Delete target',
    'engage.namePh': 'Name of target / program / box',
    'engage.notesPh': 'Target notes (markdown): creds, ports, leads…',
    'engage.name': 'Name',
    'engage.status': 'Status',
    'engage.hostLabel': 'Host / IP  →  {TARGET}',
    'engage.lhostLabel': 'LHOST  →  {LHOST}',
    'engage.scope': 'Scope',
    'engage.scopePh': '*.target.com, in-scope hosts…',
    'engage.addFinding': '＋ Finding',
    'engage.notesHead': '🗒 Notes',
    'engage.noFindings': 'no findings yet - add the first one',
  },
};
export default p;
