// Export the seeded REFERENCE content from the SQLite DB into static JSON files,
// so the app can run fully client-side on GitHub Pages (no server). User data
// (custom entries, notes, favorites, targets, findings, checklist progress) is
// NOT exported — on the static build it lives per-browser in IndexedDB.
//
// Output → web/public/data/ (git-ignored; regenerated by the Pages CI):
//   entries-<type>.json   full reference entries of each type (payload, command, …)
//   search-index.json     lightweight {id,type,title,category,tags,snippet} for ⌘K
//   checklists.json       checklist DEFINITIONS (slug,title,category,sort,research,sections)
//   manifest.json         { types: {type: count}, checklists: n }
//
// Run:  npm run export-static
import { db, getSetting } from '../server/db';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, '..', 'web', 'public', 'data');
mkdirSync(OUT, { recursive: true });

const toEntry = (r: any) => ({
  ...r,
  tags: r.tags ? JSON.parse(r.tags) : [],
  meta: r.meta ? JSON.parse(r.meta) : null,
  is_custom: false,
  is_favorite: false,
  notes: null,
});

// Checklist DEFINITIONS (locale-independent for now; progress lives per-browser in IndexedDB).
// Shared at data/checklists.json — both languages read the same definitions.
const cls = (db.prepare('SELECT * FROM checklists ORDER BY sort, slug').all() as any[]).map((r) => ({
  slug: r.slug, title: r.title, category: r.category, sort: r.sort,
  research: r.research ?? '', sections: r.sections ? JSON.parse(r.sections) : [],
}));
writeFileSync(join(OUT, 'checklists.json'), JSON.stringify(cls));
// English checklists (RU item keys + EN text, built at seed time). Falls back to RU defs.
writeFileSync(join(OUT, 'checklists-en.json'), getSetting('checklists:en') || JSON.stringify(cls));

// Reference entries (is_custom=0), exported per locale into data/<locale>/.
const LOCALES = ['ru', 'en'] as const;
for (const locale of LOCALES) {
  const outDir = join(OUT, locale);
  mkdirSync(outDir, { recursive: true });
  const rows = (db.prepare('SELECT * FROM entries WHERE is_custom=0 AND locale=? ORDER BY is_favorite DESC, id').all(locale) as any[]).map(toEntry);

  const byType: Record<string, any[]> = {};
  for (const e of rows) (byType[e.type] ??= []).push(e);
  for (const [type, arr] of Object.entries(byType)) {
    writeFileSync(join(outDir, `entries-${type}.json`), JSON.stringify(arr));
  }

  // Lightweight search index (no full bodies → fast ⌘K; full entry loaded on open).
  const index = rows.map((e) => ({
    id: e.id, type: e.type, title: e.title, category: e.category,
    tags: e.tags, snippet: (e.body ?? '').replace(/\s+/g, ' ').trim().slice(0, 160),
  }));
  writeFileSync(join(outDir, 'search-index.json'), JSON.stringify(index));

  const manifest = {
    types: Object.fromEntries(Object.entries(byType).map(([t, a]) => [t, a.length])),
    checklists: cls.length,
  };
  writeFileSync(join(outDir, 'manifest.json'), JSON.stringify(manifest));

  console.log(`[export-static] ${locale}: ${rows.length} entries across ${Object.keys(byType).length} types → web/public/data/${locale}/`);
}
console.log(`[export-static] ${cls.length} checklists → web/public/data/checklists.json`);
